#Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'TagIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TagIt
  pod 'RealmSwift'
  pod 'RxSwift', '~> 4.5'
  pod 'RxCocoa', '~> 4.5'
end
